(part "SRP2313AA-101M"
    (packageRef "INDPM235220X1300N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "652-SRP2313AA-101M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/SRP2313AA-101M?qs=gZXFycFWdANfITbqx%252BPtOw%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "SRP2313AA-101M")
    (property "Description" "Fixed Inductors Ind,23.5x22x12.6mm 100uH20%,11A, shdSMD")
    (property "Datasheet_Link" "")
    (property "symbolName1" "SRP2313AA-101M")
)
