(part "XT30UPB-F"
    (packageRef "XT30UPBF")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Amass")
    (property "Manufacturer_Part_Number" "XT30UPB-F")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Socket; DC supply; XT30; female; PIN: 2; on PCBs; THT; Colour: yellow")
    (property "Datasheet_Link" "https://www.tme.eu/Document/81f11ca924696756331f21b972812074/XT30PB-F.pdf")
    (property "symbolName1" "XT30UPB-F")
)
