(part "MAX17639AFN+"
    (packageRef "MAX17793AFN")
    (interface
        (port "1" (symbPinId 1) (portName "BST") (portType INOUT))
        (port "2" (symbPinId 2) (portName "LX_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IN_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PGND_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "PGND_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "LX_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "PGND_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PGND_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "IN_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "EN/UVLO") (portType INOUT))
        (port "11" (symbPinId 11) (portName "EXTVCC") (portType INOUT))
        (port "12" (symbPinId 12) (portName "FB_1") (portType INOUT))
        (port "13" (symbPinId 13) (portName "RT") (portType INOUT))
        (port "14" (symbPinId 14) (portName "SS") (portType INOUT))
        (port "15" (symbPinId 15) (portName "MODE/SYNC") (portType INOUT))
        (port "16" (symbPinId 16) (portName "%RESET%/TJ") (portType INOUT))
        (port "17" (symbPinId 17) (portName "SGND") (portType INOUT))
        (port "18" (symbPinId 18) (portName "INTVCC_1") (portType INOUT))
        (port "19" (symbPinId 19) (portName "EP") (portType INOUT))
        (port "20" (symbPinId 20) (portName "INTVCC_2") (portType INOUT))
        (port "21" (symbPinId 21) (portName "PGND_5") (portType INOUT))
        (port "22" (symbPinId 22) (portName "PGND_6") (portType INOUT))
        (port "23" (symbPinId 23) (portName "PGND_7") (portType INOUT))
        (port "24" (symbPinId 24) (portName "PGND_8") (portType INOUT))
        (port "25" (symbPinId 25) (portName "FB_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "MAX17639AFN+")
    (property "Description" "3V to 36V, 6A/8A/10A, 12A Peak, High-Efficiency, Synchronous Step-Down DC-DC Converter")
    (property "Datasheet_Link" "https://www.analog.com/MAX17639/datasheet")
    (property "symbolName1" "MAX17639AFN+")
)
