(part "NFM18CC221R1C3D"
    (packageRef "NFM18CC101R1C3D")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "NFM18CC221R1C3D")
    (property "Description" "Capacitor L=1.6mm W=0.8mm T=0.6mm")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/A01X/3TERMINAL-EN.pdf")
    (property "symbolName1" "NFM18CC221R1C3D")
)
