(part "PA2754NL"
    (packageRef "PA2754NL")
    (interface
        (port "1" (symbPinId 1) (portName "PRI_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PRI_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SEC_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SEC_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Mouser_Part_Number" "673-PA2754NL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Pulse-Electronics/PA2754NL?qs=%252BUGZmmosPSIl0ME75doAGQ%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "PA2754NL")
    (property "Description" "Common Mode Chokes / Filters 3.75mOhms 215uH 10A SMD Toroid Choke")
    (property "Datasheet_Link" "https://www.digikey.ph/en/products/detail/pulse-electronics/PA2754NL/3025638")
    (property "symbolName1" "PA2754NL")
)
